In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
data = pd.read_csv("Data.csv")
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
data.shape
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [4]:
data.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [5]:
data["Age"]

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [6]:
data[["Age","Salary"]]

Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0      NaN
5  35.0  58000.0
6   NaN  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [7]:
X=data.iloc[:,:-1]
X


Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [8]:
Y=data.iloc[:,-1]
Y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [9]:
# X['Age']=X['Age'].fillna(int(X['Age'].mean()))
# X

In [10]:
# X['Salary']=X['Salary'].fillna(X['Salary'].mean())
# X

In [11]:
X.fillna({"Salary":X["Salary"].mean(),"Age":int(X["Age"].mean())},inplace=True)
X

Country   Age        Salary
0   France  44.0  72000.000000
1    Spain  27.0  48000.000000
2  Germany  30.0  54000.000000
3    Spain  38.0  61000.000000
4  Germany  40.0  63777.777778
5   France  35.0  58000.000000
6    Spain  38.0  52000.000000
7   France  48.0  79000.000000
8  Germany  50.0  83000.000000
9   France  37.0  67000.000000

In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [13]:
type(X)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],remainder="passthrough")
X1=ct.fit_transform(X)
X1

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [14]:
X1=X1[:,1:]
X1

array([[0.00000000e+00, 0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [0.00000000e+00, 1.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 0.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 3.80000000e+01, 5.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 0.00000000e+00, 5.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 0.00000000e+00, 3.70000000e+01, 6.70000000e+04]])

In [15]:
X2=pd.get_dummies(X,drop_first=True)
X2

Age        Salary  Country_Germany  Country_Spain
0  44.0  72000.000000                0              0
1  27.0  48000.000000                0              1
2  30.0  54000.000000                1              0
3  38.0  61000.000000                0              1
4  40.0  63777.777778                1              0
5  35.0  58000.000000                0              0
6  38.0  52000.000000                0              1
7  48.0  79000.000000                0              0
8  50.0  83000.000000                1              0
9  37.0  67000.000000                0              0

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le=LabelEncoder()
Y=le.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X2,Y,random_state=0,train_size=0.8,test_size=0.2)

In [19]:
X_train

Age        Salary  Country_Germany  Country_Spain
4  40.0  63777.777778                1              0
9  37.0  67000.000000                0              0
1  27.0  48000.000000                0              1
6  38.0  52000.000000                0              1
7  48.0  79000.000000                0              0
3  38.0  61000.000000                0              1
0  44.0  72000.000000                0              0
5  35.0  58000.000000                0              0

In [20]:
X_test

Age   Salary  Country_Germany  Country_Spain
2  30.0  54000.0                1              0
8  50.0  83000.0                1              0

In [21]:
Y_test

array([0, 0])

In [22]:
Y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [28]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train1=scaler.transform(X_train)
X_train1

array([[0.61904762, 0.50896057, 1.        , 0.        ],
       [0.47619048, 0.61290323, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.52380952, 0.12903226, 0.        , 1.        ],
       [1.        , 1.        , 0.        , 0.        ],
       [0.52380952, 0.41935484, 0.        , 1.        ],
       [0.80952381, 0.77419355, 0.        , 0.        ],
       [0.38095238, 0.32258065, 0.        , 0.        ]])

In [24]:
# X_test2=scaler.transform(X_test)
# X_test2

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

ct = ColumnTransformer([('somename', StandardScaler(), ['Age', 'Salary'])], remainder='passthrough')

X_train2=ct.fit_transform(X_train)
X_train2

array([[ 0.27978024,  0.12381479,  1.        ,  0.        ],
       [-0.23673712,  0.46175632,  0.        ,  0.        ],
       [-1.95846165, -1.53093341,  0.        ,  1.        ],
       [-0.06456467, -1.11141978,  0.        ,  1.        ],
       [ 1.65715986,  1.7202972 ,  0.        ,  0.        ],
       [-0.06456467, -0.16751412,  0.        ,  1.        ],
       [ 0.96847005,  0.98614835,  0.        ,  0.        ],
       [-0.58108203, -0.48214934,  0.        ,  0.        ]])

In [27]:
X_test2=ct.fit_transform(X_test)
X_test2

array([[-1., -1.,  1.,  0.],
       [ 1.,  1.,  1.,  0.]])